development:
  adapter: postgresql
  encoding: unicode
  database: awesome_restaurant_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: awesome_restaurant_test
  pool: 5
  username:
  password: